[package]
version = "0.1.0"
name = "jwt-program"
edition = "2021"

[dependencies]
sp1-zkvm = "5.0.0"
rsa = "0.9.6"
sha2 = { version =  "0.10.8", package = "sha2", features = ["oid"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
base64 = "0.22.1"