name: Build and test contracts

on:
  pull_request:
    branches:
      - "*"

jobs:
  compile:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install func-js
        run: make funcjs

      - name: Build contracts
        run: make build

  unit_tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install testuite dependencies
        working-directory: tests/
        run: npm install

      - name: Run tests
        run: make tests
